#!/bin/bash
if (( $# == 1 )) && ([ "$1" = "start" ] || [ "$1" = "stop" ] || [ "$1" = "restart" ]); then
sudo systemctl $1 iobroker
elif [ "$1" = "fix" ]; then
curl -sL https://iobroker.net/fix.sh | bash -
else
sudo -H -u iobroker node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js $@
fi
